### ISSUE TITLE
GitHub Pages demo?

### ISSUE THREAD

**Issue by lolmaus** [AlwarG/ember-mirage-gen#1]
Hi! 

It would be nice to see the addon in action. You could build it in dev mode and deploy to GitHub Pages!

**Comment by AlwarG** [comment]
https://alwarg.github.io/mirage-gen-demo/

**Comment by lolmaus** [comment]
Thanks for the effort!

I asked for the demo in order to see what the addon is offering specifically, because I could not fully understand it from the readme.

But the demo app is *very* different from the screenshots in the readme. I don't understand how they relate to each other and I'm even more confused.

There's a note in the demo: "Note: For comparision try address(For factory) and company(For fixture) node". It's not clear how I'm supposed to try something for comparison because there's only one interactive element on the page: the <kbd>Get Users</kbd> button.

There's also an issue with the app redirecting to `/mirage-gen-demo/mirage-gen-demo/`. If I refresh the page, GitHub Pages yields a 404 error.

**Comment by AlwarG** [comment]
Thank you for reaching me.
I will improve and I will update you.
